#!/bin/sh
# Xsetup - run as root before the login dialog appears

#!/bin/sh
intern=eDP
extern=HDMI-A-0

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto
else
    xrandr --output "$intern" --off --output "$extern" --mode 1920x1080 --rate 60
fi
